### ISSUE TITLE
版本问题

### ISSUE THREAD

**Issue by myliweihao** [ali-sdk/alipay-sdk#2]
请问有没有alpay-sdk js版本的?ts用起来不太顺手。

**Comment by troyeagle** [comment]
同樣的問題。。我是用ts編譯出來js然後輸入進去的。參考一下

```javascript
const alipaySdk = new AlipaySdk.default(AlipaySdkConfig);
const formData = new AlipayFormData.default();
```

**Comment by tudou527** [comment]
JS 可以这么用

```
const AlipaySDK = require('alipay-sdk').default;
const alipaySdk = new AlipaySDK({
  //... config
});

alipaySdk.exec('alipay.system.oauth.token', {
    grantType: 'authorization_code',
    code: 'code',
    refreshToken: 'token'
}).then(res => {
    console.log(res);
}).catch((err) => {
    console.log(err);
});
```

**Comment by heiheiLqq** [comment]
const AlipaySDK = require('alipay-sdk').default;
const fs = require('fs')

const alipaySdk = new AlipaySDK({
    appId: '2018081661053647',
    privateKey: fs.readFileSync(__dirname + '/../secretKey/private-key.pem', 'ascii'),
    alipayPublicKey: fs.readFileSync(__dirname+'/../secretKey/public-key.pem', 'ascii'),
});

async function getAccessToken (auth_code,refreshToken) {

    alipaySdk.exec('alipay.system.oauth.token', {
        grantType: 'authorization_code',
        code: auth_code,
        refreshToken: ''
    }).then(res => {
        console.log(res);
    }).catch((err) => {
        console.log(err);
    });

}

报异常

TypeError: [AlipaySdk]exec error
    at WeakMap.set (native)
    at mapObj (/Users/zhuangzihao/i-counting/customer_api/node_modules/map-obj/index.js:23:7)
    at camelCaseConvert (/Users/zhuangzihao/i-counting/customer_api/node_modules/camelcase-keys/index.js:16:9)
    at module.exports (/Users/zhuangzihao/i-counting/customer_api/node_modules/camelcase-keys/index.js:39:9)
    at config.urllib.request.then (/Users/zhuangzihao/i-counting/customer_api/node_modules/alipay-sdk/lib/alipay.js:251:52)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by tudou527** [comment]
看起来是 `customer_api/node_modules/alipay-sdk/lib/alipay.js#251` 报错了，提供个可以重现的 demo 到  tudou527#gmail.com  吧
